env: "local"
http_server:
  address: "0.0.0.0:8000"
  timeout: 5s
  idle_timeout: 10s
mailbox:
  from: "x.platform.noreply@gmail.com"
  password: "rbnk dhdj mghn blzo"
  host: "smtp.gmail.com"
  port: "587
